MRBEE_SuSiE_Independent=function(by,bX,byse,bXse,Rxy,Nmin=F,Lvec=c(1:min(10,nrow(bX))),pip.thres=0.5,tauvec=seq(3,50,by=2),max.iter=100,max.eps=0.001,susie.iter=100,ebic.theta=0,ebic.gamma=1,empirical.variance.lower=0.2,empirical.variance.upper=100,reliability.thres=0.5,rho=2,maxdiff=1.5,sampling.time=100,sampling.frac=0.5,sampling.iter=5,theta.ini=F,gamma.ini=F){
if(is.vector(bX)==T){
A=MRBEE_IPOD_UV(by=by,bX=bX,byse=byse,bXse=bXse,Rxy=Rxy,Nmin=Nmin,tauvec=tauvec,max.iter=max.iter,max.eps=max.eps,ebic.gamma=ebic.gamma,maxdiff=maxdiff,theta.ini=theta.ini,gamma.ini=gamma.ini,reliability.thres=reliability.thres)
}else{
########################### Basic information #######################
cat("MRBEE SuSiE:\n")
cat("preparing data -> ")
by=by/byse
byseinv=1/byse
bX=bX*byseinv
bXse=bXse*byseinv
byse1=byse
byse=byse/byse
m=nrow(bX)
p=ncol(bX)
if(Nmin==F){
Nmin=m
}
cluster.index=c(1:m)
BtB=matrixMultiply(t(bX),bX)
BtB=t(BtB)/2+BtB/2
r=reliability.adj(bX,bXse,Theta="identity",thres=reliability.thres)
r=c(r,1)
Rxy=t(t(Rxy)*r)*r
RxyList=IVweight(byse,bXse,Rxy)
Rxyall=biasterm(RxyList=RxyList,c(1:m))
############################ Initial Estimate #######################
if(theta.ini[1]==F){
fit0=MRBEE_IMRP(by=by,bX=bX,byse=byse,bXse=bXse,Rxy=Rxy,var.est="variance",FDR="Sidak")
gamma.ini=gamma.ini1=fit0$gamma
theta.ini=theta.ini1=fit0$theta
}else{
gamma.ini=gamma.ini1=gamma.ini/byse1
theta.ini=theta.ini1=theta.ini
}
############################## Tuning Parameter ######################
w=length(tauvec)
q=length(Lvec)
Btheta.ipod=array(0,c(p,w))
Bgamma.ipod=array(0,c(m,w))
Btheta.susie=array(0,c(p,q))
Bgamma.susie=array(0,c(m,q))
Bbic.ipod=c(1:w)
Bbic.susie=c(1:q)
cat("selecting optimal tau in IPOD and L in SuSiE -> ")
############################ Selecting Tau in Step 1###########################
for(j in length(tauvec):1){
error=1
iter=1
theta=theta.ini
gamma=gamma.ini
gamma1=gamma
delta=gamma1*0
while(error>max.eps&iter<max.iter){
theta1=theta
indvalid=which(gamma1==0)
if(length(indvalid)==m){
Rxysum=Rxyall
}else{
Rxysum=Rxyall-biasterm(RxyList=RxyList,setdiff(1:m,indvalid))
}
Hinv=matrixInverse(BtB-Rxysum[1:p,1:p])
g=matrixVectorMultiply(t(bX),by-gamma)-Rxysum[1:p,p+1]
theta=c(matrixVectorMultiply(Hinv,g))
if((norm(theta,"2")/norm(theta.ini,"2"))>maxdiff){
theta=theta/norm(theta,"2")*maxdiff*norm(theta.ini1,"2")
}
########################### update gamma ############################
gamma=(by-matrixVectorMultiply(bX,theta)-delta+rho*gamma1)/(1+rho)
gamma1=mcp(gamma+delta/rho,tauvec[j]/rho)
delta=delta+rho*(gamma-gamma1)
iter=iter+1
if(iter>3){
error=max(abs(theta-theta1))
}
}
Btheta.ipod[,j]=theta
Bgamma.ipod[,j]=gamma1
df1=sum(gamma1!=0)
res=c(by-matrixVectorMultiply(bX,theta)-gamma)
rss=sum(res^2)
Bbic.ipod[j]=log(rss)*Nmin+(log(Nmin)+ebic.gamma*log(m))*df1
}
jstar=which.min(Bbic.ipod)
theta.ini=Btheta.ipod[,jstar]
gamma.ini=Bgamma.ipod[,jstar]
indvalid=which(gamma.ini==0)
res=by-matrixVectorMultiply(bX,theta.ini)-gamma.ini
rss=sum(res^2)
empirical.variance.formula=min(rss/(m-sum(theta.ini!=0)-sum(gamma.ini!=0)),empirical.variance.upper)
empirical.variance.formula=max(empirical.variance.formula,empirical.variance.lower)
######################## selecting L in Step 1 ###############################
for(v in length(Lvec):1){
theta=theta.ini
gamma=gamma.ini
gamma1=gamma
delta=gamma1*0
error=1
iter=1
empirical.variance=empirical.variance.formula
while(error>max.eps&iter<max.iter){
theta1=theta
indvalid=which(gamma1==0)
if(length(indvalid)==m){
Rxysum=Rxyall
}else{
Rxysum=Rxyall-biasterm(RxyList=RxyList,setdiff(1:m,indvalid))
}
res.theta=by-gamma
XtX=BtB
Xty=matrixVectorMultiply(t(bX),res.theta)
yty=sum(res.theta^2)
fit.theta=susie_suff_stat(XtX=BtB,Xty=Xty,yty=yty,n=m,L=Lvec[v],residual_variance=empirical.variance,estimate_prior_method="EM",intercept=F,estimate_residual_variance=F,max_iter=susie.iter)
theta=coef.susie(fit.theta)[-1]*(fit.theta$pip>pip.thres)
indtheta=which(theta!=0)
if(length(indtheta)==1){
xtx=XtX[indtheta,indtheta]-Rxysum[indtheta,indtheta]
xty=Xty[indtheta]-Rxysum[indtheta,p+1]
theta[indtheta]=xty/xtx
}
if(length(indtheta)>1){
XtX=XtX[indtheta,indtheta]-Rxysum[indtheta,indtheta]
Xty=Xty[indtheta]-Rxysum[indtheta,p+1]
theta[indtheta]=c(solve(XtX)%*%Xty)
}
if((norm(theta,"2")/norm(theta.ini1,"2"))>maxdiff){
theta=theta/norm(theta,"2")*maxdiff*norm(theta.ini1,"2")
}
gamma=(by-matrixVectorMultiply(bX,theta)-delta+rho*gamma1)/(1+rho)
gamma1=mcp(gamma+delta/rho,tauvec[jstar]/rho)
delta=delta+rho*(gamma-gamma1)
res=by-matrixVectorMultiply(bX,theta)-gamma1
rss=sum(res^2)
empirical.variance=rss/(m-sum(gamma1!=0)-min(sum(theta!=0),Lvec[v]))
empirical.variance=max(empirical.variance,empirical.variance.lower)
empirical.variance=min(empirical.variance,empirical.variance.upper)
iter=iter+1
if(iter>3){
error=max(abs(theta-theta1))
}
}
Btheta.susie[,v]=theta
Bgamma.susie[,v]=gamma1
df1=sum(gamma1!=0)
df2=min(Lvec[v],sum(theta!=0))
Bbic.susie[v]=log(rss)*Nmin+df2*(log(Nmin)+log(p)*ebic.theta)+(log(Nmin)+ebic.gamma*log(m))*df1
}
vstar=which.min(Bbic.susie)
theta.ini=Btheta.susie[,vstar]
gamma.ini=Bgamma.susie[,vstar]
indvalid=which(gamma.ini==0)
res=by-matrixVectorMultiply(bX,theta.ini)-gamma.ini
rss=sum(res^2)
empirical.variance.formula=min(rss/(m-sum(theta.ini!=0)-sum(gamma.ini!=0)),empirical.variance.upper)
empirical.variance.formula=max(empirical.variance.formula,empirical.variance.lower)
######################## selecting tau in Step 2###############################
cat("selecting optimal L in SuSiE -> ")
for(j in length(tauvec):1){
theta=theta.ini
gamma=gamma.ini
gamma1=gamma
delta=gamma1*0
error=1
iter=1
empirical.variance=empirical.variance.formula
while(error>max.eps&iter<max.iter){
theta1=theta
indvalid=which(gamma1==0)
if(length(indvalid)==m){
Rxysum=Rxyall
}else{
Rxysum=Rxyall-biasterm(RxyList=RxyList,setdiff(1:m,indvalid))
}
res.theta=by-gamma
XtX=BtB
Xty=matrixVectorMultiply(t(bX),res.theta)
yty=sum(res.theta^2)
fit.theta=susie_suff_stat(XtX=BtB,Xty=Xty,yty=yty,n=m,L=Lvec[vstar]+1,residual_variance=empirical.variance,estimate_prior_method="EM",intercept=F,estimate_residual_variance=F,max_iter=susie.iter)
theta=coef.susie(fit.theta)[-1]*(fit.theta$pip>pip.thres)
indtheta=which(theta!=0)
if(length(indtheta)==1){
xtx=XtX[indtheta,indtheta]-Rxysum[indtheta,indtheta]
xty=Xty[indtheta]-Rxysum[indtheta,p+1]
theta[indtheta]=xty/xtx
}
if(length(indtheta)>1){
XtX=XtX[indtheta,indtheta]-Rxysum[indtheta,indtheta]
Xty=Xty[indtheta]-Rxysum[indtheta,p+1]
theta[indtheta]=c(solve(XtX)%*%Xty)
}
if((norm(theta,"2")/norm(theta.ini1,"2"))>maxdiff){
theta=theta/norm(theta,"2")*maxdiff*norm(theta.ini1,"2")
}
gamma=(by-matrixVectorMultiply(bX,theta)-delta+rho*gamma1)/(1+rho)
gamma1=mcp(gamma+delta/rho,tauvec[j]/rho)
delta=delta+rho*(gamma-gamma1)
res=by-matrixVectorMultiply(bX,theta)-gamma1
rss=sum(res^2)
empirical.variance=rss/(m-sum(gamma1!=0)-min(sum(theta!=0),Lvec[v]))
empirical.variance=max(empirical.variance,empirical.variance.lower)
empirical.variance=min(empirical.variance,empirical.variance.upper)
iter=iter+1
if(iter>3){
error=max(abs(theta-theta1))
}
}
Btheta.susie[,j]=theta
Bgamma.susie[,j]=gamma1
df1=sum(gamma1!=0)
df2=min(Lvec[vstar],sum(theta!=0))
Bbic.susie[j]=log(rss)*Nmin+df2*(log(Nmin)+log(p)*ebic.theta)+(log(Nmin)+ebic.gamma*log(m))*df1
}
jstar=which.min(Bbic.ipod)
theta.ini=Btheta.ipod[,jstar]
gamma.ini=Bgamma.ipod[,jstar]
indvalid=which(gamma.ini==0)
res=by-matrixVectorMultiply(bX,theta.ini)-gamma.ini
rss=sum(res^2)
empirical.variance.formula=min(rss/(m-sum(theta.ini!=0)-sum(gamma.ini!=0)),empirical.variance.upper)
empirical.variance.formula=max(empirical.variance.formula,empirical.variance.lower)
######################## selecting L in Step 2###############################
for(v in length(Lvec):1){
theta=theta.ini
gamma=gamma.ini
gamma1=gamma
delta=gamma1*0
error=1
iter=1
empirical.variance=empirical.variance.formula
while(error>max.eps&iter<max.iter){
theta1=theta
indvalid=which(gamma1==0)
if(length(indvalid)==m){
Rxysum=Rxyall
}else{
Rxysum=Rxyall-biasterm(RxyList=RxyList,setdiff(1:m,indvalid))
}
res.theta=by-gamma
XtX=BtB
Xty=matrixVectorMultiply(t(bX),res.theta)
yty=sum(res.theta^2)
fit.theta=susie_suff_stat(XtX=BtB,Xty=Xty,yty=yty,n=m,L=Lvec[v],residual_variance=empirical.variance,estimate_prior_method="EM",intercept=F,estimate_residual_variance=F,max_iter=susie.iter)
theta=coef.susie(fit.theta)[-1]*(fit.theta$pip>pip.thres)
indtheta=which(theta!=0)
if(length(indtheta)==1){
xtx=XtX[indtheta,indtheta]-Rxysum[indtheta,indtheta]
xty=Xty[indtheta]-Rxysum[indtheta,p+1]
theta[indtheta]=xty/xtx
}
if(length(indtheta)>1){
XtX=XtX[indtheta,indtheta]-Rxysum[indtheta,indtheta]
Xty=Xty[indtheta]-Rxysum[indtheta,p+1]
theta[indtheta]=c(solve(XtX)%*%Xty)
}
if((norm(theta,"2")/norm(theta.ini1,"2"))>maxdiff){
theta=theta/norm(theta,"2")*maxdiff*norm(theta.ini1,"2")
}
gamma=(by-matrixVectorMultiply(bX,theta)-delta+rho*gamma1)/(1+rho)
gamma1=mcp(gamma+delta/rho,tauvec[jstar]/rho)
delta=delta+rho*(gamma-gamma1)
res=by-matrixVectorMultiply(bX,theta)-gamma1
rss=sum(res^2)
empirical.variance=rss/(m-sum(gamma1!=0)-min(sum(theta!=0),Lvec[v]))
empirical.variance=max(empirical.variance,empirical.variance.lower)
empirical.variance=min(empirical.variance,empirical.variance.upper)
iter=iter+1
if(iter>3){
error=max(abs(theta-theta1))
}
}
Btheta.susie[,v]=theta
Bgamma.susie[,v]=gamma1
df1=sum(gamma1!=0)
df2=min(Lvec[v],sum(theta!=0))
Bbic.susie[v]=log(rss)*Nmin+df2*(log(Nmin)+log(p)*ebic.theta)+(log(Nmin)+ebic.gamma*log(m))*df1
}
######################## Final Estimate #################################
vstar=which.min(Bbic.susie)
error=1
iter=1
theta.ini=Btheta.susie[,vstar]
gamma.ini=Bgamma.susie[,vstar]
indvalid=which(gamma.ini==0)
res=c(by-matrixVectorMultiply(bX,theta.ini)-gamma.ini)
rss=sum(res^2)
empirical.variance.formula=min(rss/(m-sum(theta.ini!=0)-sum(gamma.ini!=0)),empirical.variance.upper)
empirical.variance.formula=min(empirical.variance.formula,empirical.variance.upper)
gamma1=gamma
delta=gamma1
empirical.variance=empirical.variance.formula
while(error>max.eps&iter<max.iter){
theta1=theta
indvalid=which(gamma1==0)
if(length(indvalid)==m){
Rxysum=Rxyall
}else{
Rxysum=Rxyall-biasterm(RxyList=RxyList,setdiff(1:m,indvalid))
}
res.theta=by-gamma
XtX=BtB
Xty=matrixVectorMultiply(t(bX),res.theta)
yty=sum(res.theta^2)
fit.theta=susie_suff_stat(XtX=BtB,Xty=Xty,yty=yty,n=m,L=Lvec[vstar],residual_variance=empirical.variance,estimate_prior_method="EM",intercept=F,estimate_residual_variance=F,max_iter=susie.iter)
theta=coef.susie(fit.theta)[-1]*(fit.theta$pip>pip.thres)
indtheta=which(theta!=0)
if(length(indtheta)==1){
xtx=XtX[indtheta,indtheta]-Rxysum[indtheta,indtheta]
xty=Xty[indtheta]-Rxysum[indtheta,p+1]
theta[indtheta]=xty/xtx
}
if(length(indtheta)>1){
XtX=XtX[indtheta,indtheta]-Rxysum[indtheta,indtheta]
Xty=Xty[indtheta]-Rxysum[indtheta,p+1]
theta[indtheta]=c(solve(XtX)%*%Xty)
}
if((norm(theta,"2")/norm(theta.ini1,"2"))>maxdiff){
theta=theta/norm(theta,"2")*maxdiff*norm(theta.ini1,"2")
}
########################### update gamma ############################
gamma=(by-matrixVectorMultiply(bX,theta)-delta+rho*gamma1)/(1+rho)
gamma1=mcp(gamma+delta/rho,tauvec[jstar]/rho)
delta=delta+rho*(gamma-gamma1)
res=c(by-matrixVectorMultiply(bX,theta)-gamma1)
rss=sum(res^2)
empirical.variance=rss/(m-sum(gamma1!=0)-min(sum(theta!=0),Lvec[vstar]))
empirical.variance=max(empirical.variance,empirical.variance.lower)
empirical.variance=min(empirical.variance,empirical.variance.upper)
iter=iter+1
if(iter>3){
error=max(abs(theta-theta1))
}
}
############################### inference #########################
cat("making inference\n")
gamma=gamma1
theta=theta
names(theta)=colnames(bX)
names(gamma)=rownames(bX)
indtheta=which(theta!=0)
indgamma=which(gamma1!=0)
indvalid=which(gamma1==0)
res=by-matrixVectorMultiply(bX,theta)-gamma1
if(sampling.time==0){
ThetaList=NULL
if(length(indtheta)==0){
indtheta=c(1:2)
}
pstar=length(indtheta)
bZ=cbind(bX[,indtheta],diag(m)[,indgamma])
bZ=as.matrix(bZ)
H=matrixMultiply(t(bZ),bZ)
H[1:pstar,1:pstar]=H[1:pstar,1:pstar]-Rxysum[indtheta,indtheta]
H=matrixInverse(H)
Hat=matrixListProduct(list(bZ,H,t(bZ)))
Hat=1-diag(Hat)
Hat[Hat<0.5]=0.5
E=-bZ*(res/Hat)
V=matrixMultiply(t(E),E)
COV=H%*%V%*%H
theta.cov=diag(p)*0
theta.cov[indtheta,indtheta]=COV[1:pstar,1:pstar]
theta.se=sqrt(diag(theta.cov))
colnames(theta.cov)=rownames(theta.cov)=names(theta.se)=colnames(bX)
}else{
ThetaList=matrix(0,sampling.time,p)
cat("Bootstrapping process:\n")
pb <- txtProgressBar(min = 0, max = sampling.time, style = 3)
for(j in 1:sampling.time) {
setTxtProgressBar(pb, j)
indj=sample(m,sampling.frac*m,replace=F)
indj <- sort(indj)
BtBj <- matrixMultiply(t(bX[indj,]),bX[indj,])
BtBj=t(BtBj)/2+BtBj/2
thetaj=theta
gammaj=gamma1j=gamma
deltaj=gammaj*0
for(jiter in 1:sampling.iter){
indvalidj <- which(gamma1j==0)
indvalidj <- intersect(indvalidj, indj)
Rxysumj <- biasterm(RxyList = RxyList, indvalidj)
res.thetaj=by[indj]-gammaj[indj]
XtXj=BtBj
Xtyj=matrixVectorMultiply(t(bX[indj,]),res.thetaj)
ytyj=sum(res.thetaj^2)
fit.thetaj=susie_suff_stat(XtX=BtBj,Xty=Xtyj,yty=ytyj,n=length(indvalidj),L=Lvec[vstar],residual_variance=empirical.variance,estimate_prior_method="EM",intercept=F,estimate_residual_variance=F,max_iter=sampling.iter,s_init=fit.theta)
thetaj=coef.susie(fit.thetaj)[-1]*(fit.thetaj$pip>pip.thres)
indthetaj=which(thetaj!=0)
if(length(indthetaj)==1){
xtxj=XtXj[indthetaj,indthetaj]-Rxysumj[indthetaj,indthetaj]
xtyj=Xtyj[indthetaj]-Rxysumj[indthetaj,p+1]
thetaj[indthetaj]=xtyj/xtxj
}
if(length(indthetaj)>1){
XtXj=XtXj[indthetaj,indthetaj]-Rxysumj[indthetaj,indthetaj]
Xtyj=Xtyj[indthetaj]-Rxysumj[indthetaj,p+1]
thetaj[indthetaj]=c(solve(XtXj)%*%Xtyj)
}
if((norm(thetaj, "2") / norm(theta.ini1, "2")) > maxdiff) {
thetaj <- thetaj / norm(thetaj, "2") * maxdiff * norm(theta.ini1, "2")
}
gammaj[indj]=(by[indj]-matrixVectorMultiply(bX[indj, ],thetaj)-deltaj[indj]+rho*gamma1j[indj])/(1+rho)
gamma1j=mcp(gammaj+deltaj/rho,tauvec[jstar]/rho)
deltaj=deltaj+rho*(gammaj-gamma1j)
}
ThetaList[j, ] <- thetaj
}
close(pb)
theta.se=colSD(ThetaList)*sqrt((m-length(indtheta))/(m-length(indtheta)-length(indgamma)))
theta.cov=cov(ThetaList)*(m-length(indtheta))/(m-length(indtheta)-length(indgamma))
colnames(theta.cov)=rownames(theta.cov)=names(theta.se)=colnames(bX)
}
A=list()
A$theta=theta
A$gamma=gamma*byse1
A$theta.se=theta.se
A$theta.cov=theta.cov
A$Bic.susie=Bbic.susie
A$Bic.ipod=Bbic.ipod
A$reliability.adjust=r
A$susie.theta=fit.theta
A$thetalist=ThetaList
}
return(A)
}
